import type { Metadata } from "next";
import localFont from "next/font/local";
import { DM_Sans, Fira_Code, Inter } from "next/font/google";
import "./globals.css";

const fontSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});

const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${fontInter.variable} ${fontMono.variable} ${fontSans.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
